import GeneratorLayout from '../components/GeneratorLayout';
import { Activity } from 'lucide-react';

export default function SymptomChecker() {
  return (
    <GeneratorLayout
      title="Symptom Checker"
      description="Enter symptoms to explore possible conditions and receive an urgency assessment."
      type="Symptom Checker"
      placeholder="e.g. I have a severe headache that started 2 hours ago, accompanied by nausea and sensitivity to light..."
      icon={Activity}
      inputLabel="Describe Symptoms in Detail"
      disclaimer="The information provided is generated by AI for educational purposes only. It is NOT a medical diagnosis. Always consult a qualified healthcare provider for medical advice."
    />
  );
}
