import GeneratorLayout from '../components/GeneratorLayout';
import { Image as ImageIcon } from 'lucide-react';

export default function VisualLearning() {
  return (
    <GeneratorLayout
      title="Visual Learning & Diagrams"
      description="Generate AI medical diagrams, flowcharts, and visual breakdowns of complex medical concepts."
      type="Visual Learning"
      placeholder="e.g. Heart anatomy diagram, Stages of pneumonia, Fracture types..."
      icon={ImageIcon}
      inputLabel="Describe the visual you need"
      disclaimer="Images generated by AI are for educational visualization only and may contain inaccuracies. Do not use for clinical decision-making."
    />
  );
}
