import { useState } from 'react';

export default function LegalAgreement({ onAccept }: { onAccept: () => void }) {
  const [accepted, setAccepted] = useState(false);

  const handleContinue = () => {
    if (accepted) {
      localStorage.setItem('medyara_legal_accepted', 'true');
      onAccept();
    }
  };

  return (
    <div className="fixed inset-0 z-[9999] bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl max-w-lg w-full p-8 shadow-2xl animate-in zoom-in-95 duration-300">
        <div className="w-16 h-16 bg-red-100 text-red-600 rounded-full flex items-center justify-center mb-6 mx-auto">
          <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        
        <h2 className="text-2xl font-bold text-center text-slate-900 mb-4">Medical Disclaimer</h2>
        
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-sm text-slate-600 leading-relaxed mb-6 max-h-48 overflow-y-auto">
          <p className="mb-3">Welcome to <strong>Medyara AI</strong>. Before using this platform, you must read and agree to the following terms:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Not Medical Advice:</strong> The content generated by Medyara AI is for informational and educational purposes only. It is <strong>NOT</strong> a substitute for professional medical advice, diagnosis, or treatment.</li>
            <li><strong>No Doctor-Patient Relationship:</strong> Using this platform does not create a doctor-patient relationship.</li>
            <li><strong>Emergencies:</strong> Do not rely on this platform in a medical emergency. If you think you may have a medical emergency, call your doctor, go to the nearest hospital emergency department, or call emergency services immediately.</li>
            <li><strong>AI Limitations:</strong> Artificial Intelligence can hallucinate or provide inaccurate information. Always consult a qualified healthcare provider regarding any medical condition or treatment.</li>
          </ul>
        </div>

        <label className="flex items-start gap-3 cursor-pointer mb-6 group">
          <div className="flex items-center h-5">
            <input 
              type="checkbox" 
              checked={accepted}
              onChange={(e) => setAccepted(e.target.checked)}
              className="w-5 h-5 rounded border-slate-300 text-blue-600 focus:ring-blue-600"
            />
          </div>
          <span className="text-sm text-slate-700 font-medium group-hover:text-slate-900">
            I have read and understood the disclaimer, and I agree to use Medyara AI responsibly.
          </span>
        </label>

        <button 
          onClick={handleContinue}
          disabled={!accepted}
          className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 disabled:text-slate-400 text-white font-bold py-3.5 rounded-xl transition-all"
        >
          I Agree, Continue to App
        </button>
      </div>
    </div>
  );
}
